export class VideoCardBean {
  public videoId: string = "";
  public title: string = "";
  public duration: number = 0;
  public desc: string = "";
  public viewCount: string = "";
  public likeCount: string = "";
  public coverUrl: string = "";
  public label: string = "";
  public authorName: string = "";
  public authorHeadUrl: string = "";
  public videoPostTime: string = "";
  public videoHigh: string = "";
  public manifest: string = "";
}